### ISSUE TITLE
Fix Channel Catchup!

### ISSUE THREAD

**Issue by shhahid7** [krreet/plugin.video.jiotv#1]
Hello, @krreet ,

Glad that you are fixing this  @addon.
if it is possible, can you please look at catchup issue.
right now channels catchup isnt working.
if possible can you fix that too?

**Comment by krreet** [comment]
Hi you can view catchup from channel context menu, press the options menu after selecting a channel .

**Comment by shhahid7** [comment]
> Hi you can view catchup from channel context menu, press the options menu after selecting a channel .

Well, its fixed from ur given way but its not fixed from Channel Guide list..
Its still giving error...
Also any idea how will Extra HD channel option will fix??
