### ISSUE TITLE
Unable to load  toblan reposatry

### ISSUE THREAD

**Issue by Devil45677** [krreet/plugin.video.jiotv#100]
It says cound connect to network server

When I am trying to add tobalan repo
![IMG_20230808_122421](https://github.com/krreet/plugin.video.jiotv/assets/141067057/ce44b355-47d2-42aa-9964-b859db9084f4)

**Comment by hritvik1** [comment]
restart Kodi

**Comment by nikhilprasad** [comment]
When I try to install from a zip file I get an error:
Failed to install addon from zip:
The dependency on repository.tolban version 2.0.1 could not be satisfied

**Comment by hritvik1** [comment]
@Devil45677 refer to this [comment](https://github.com/krreet/plugin.video.jiotv/issues/98#issuecomment-1668102552)

**Comment by nikhilprasad** [comment]
> @nikhilprasad refer to this [comment](https://github.com/krreet/plugin.video.jiotv/issues/98#issuecomment-1668102552)

Thanks. This resolved the issue.

**Comment by Devil45677** [comment]
I have installed taballen an jio 2.3.9.....
But still it's taking time to switch channel

It's taking time to switch from one channel to another

**Comment by hritvik1** [comment]
@Devil45677 Try enabling 'use channel API 3.0' in jiotv's settings

**Comment by imsurajy** [comment]
> It says cound connect to network server
> 
> When I am trying to add tobalan repo ![IMG_20230808_122421](https://user-images.githubusercontent.com/141067057/259011064-ce44b355-47d2-42aa-9964-b859db9084f4.jpg)

First of all, clear data for Kodi and then download the Tobalan repository [from here](https://tobalan.github.io/) now follow the same process to install this repository. Although channels are taking a very long time to switch between in this plugin too.

**Comment by Devil45677** [comment]
Still taking time to load channel..... It s taking to much time  to switch channel.... 

Even after enabling api 3.0

**Comment by Devil45677** [comment]
Any one

**Comment by hritvikAP** [comment]
@Devil45677 Is it taking longer than 2-3 seconds?

**Comment by hritvik1** [comment]
@Devil45677 Is it taking longer than 2-3 sec.?

**Comment by imsurajy** [comment]
Yes.. it takes around 60 sec to switch channels in my amazon fire tv, even after enabling 3.0 api as well as with the latest plugin I found no changes. The same problem persists.

**Comment by hritvik1** [comment]
What 60 sec.!!! For me, it's about 1-2 sec. only.

**Comment by hritvik1** [comment]
@imsurajy For me, it's about 2-3 sec. only.

**Comment by imsurajy** [comment]
@hritvik1 bro are you using Amazon Firetv stick, if yes which version of Kodi + Which repo (Tabolan or Botallen) are you using? Please help!

**Comment by hritvik1** [comment]
@imsurajy I've both a FireTV stick and an Android TV. and I'm using the most recent version of Kodi from the app store/play store, as well as the most recent version of the TobAlan repo.

**Comment by hritvik1** [comment]
@imsurajy Maybe there's an issue with your network.

**Comment by imsurajy** [comment]
@hritvik1 bro, thanks for dragging my attention. I got the root cause of getting too much buffering while switching channels, you were right the problem was in my wifi network even with Airtel Fibre broadband it was having issues, don't know why but as soon as I connect FireTV to my phone's hotspot, Jio tv working smoothly and channels switching is super fast too (2-3 sec).
I suspect the problem may be with the ISP or static IP, which is blocking Koditv access.

**Comment by Devil45677** [comment]
@hritvik1 @imsurajy  thanks for help.... Correct there is a problem in..... Airtel broad band router...... If we give.... Connection from hotspot from mobile.... It's working fine.... Switching channel taking less time...

**Comment by Devil45677** [comment]
Thanks

**Comment by hritvik1** [comment]
@imsurajy @Devil45677 There's a chance that the router's default firewall is blocking API requests. In this case, you can contact your ISP. You might also try enabling UPnP on your router. This isn't very related, but you could give it a shot.

**Comment by imsurajy** [comment]
@hritvik1 @Devil45677 Thanks for your suggestions, I appreciate it. As of now I have reset my Airtel router and the problem is completely solved for now, but let's see in the long run how it sustains.
