### ISSUE TITLE
Is there a hotstar video plugin like jio we use

### ISSUE THREAD

**Issue by ranjeets9** [krreet/plugin.video.jiotv#115]
Is there a hotstar video plugin like jio we use

    krreet
    /
    plugin.video.jiotv

**Comment by technofreak24** [comment]
> @ranjeets9  Is there a hotstar video plugin like jio we use

Yes there is a **Disney+ Hotstar** video plugin for KODI since some years started by [BotAllen](https://github.com/botallen/plugin.video.botallen.hotstar) till 2022 and then onwards by [AjayK](https://github.com/Vikassm73/AjaykRepo)

Here is a screenshot of it:
![IMG_20230830_152210_032420](https://github.com/krreet/plugin.video.jiotv/assets/121749085/db9ee859-2c46-490b-89c2-083c4fa10bda)

**Comment by ranjeets9** [comment]
> > @ranjeets9  Is there a hotstar video plugin like jio we use
> 
> Yes there is a **Disney+ Hotstar** video plugin for KODI since some years started by [BotAllen](https://github.com/botallen/plugin.video.botallen.hotstar) till 2022 and then onwards by [AjayK](https://github.com/Vikassm73/AjaykRepo)
> 
> Here is a screenshot of it: ![IMG_20230830_152210_032420](https://private-user-images.githubusercontent.com/121749085/291065982-db9ee859-2c46-490b-89c2-083c4fa10bda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTc0NTEsIm5iZiI6MTcwMjk5NzE1MSwicGF0aCI6Ii8xMjE3NDkwODUvMjkxMDY1OTgyLWRiOWVlODU5LTJjNDYtNDkwYi04OWMyLTA4M2M0ZmExMGJkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNDQ1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmM2YzllMTljOWU5NjI0MTMwOThjYWViYWM3YzYxM2NjMjI3MGViZTQyMDkyMjJmNDAyNjdhYjdiZWIwODEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QhG283qkpyDfSknBfNC3-yujhIdw6DMdEaavNXYW9X4)

Could you please tell me how to add / instal the plugin or any vidoe reference would help thx much appreciated

**Comment by ranjeets9** [comment]
> Install this repository as Source in KODI File Manager https://github.com/Vikassm73/AjaykRepo/raw/main/Zips/repository.ajayk-1.1.zip Then restart KODI and from the installed repository, install the video addons that you want like Hotstar or JioCinema.

Perfect it worked thx a lot for your help
