### ISSUE TITLE
Sony channel fix (temporary)

### ISSUE THREAD

**Issue by zenom141** [krreet/plugin.video.jiotv#116]

**Comment by Swappea** [comment]
@zenom141  WIll this work on firestick tv?

**Comment by technofreak24** [comment]
> @Swappea  WIll this work on firestick tv?

It is very laggy on FireTV Stick or Android Box
For FireTV Stick, it is better to use KODI with latest fixed addon. Message me on Discord @vin24 to join our server.

**Comment by Exonymos** [comment]
> @zenom141  WIll this work on firestick tv?

Yes, I just checked it on my firestick and also the Sony channels are working
Just install it like any apk file
