### ISSUE TITLE
Finally Sony Chanel are working with new plugin 

### ISSUE THREAD

**Issue by zenom141** [krreet/plugin.video.jiotv#122]
Hello, 

i found the new kodi plugin where all sony channels are working, along with other chanels. here is the discord link:

https://discord.com/invite/bYSv8v6E

also plugin file. 
[plugin.video.jiotv-1.0.15.zip](https://github.com/krreet/plugin.video.jiotv/files/14179339/plugin.video.jiotv-1.0.15.zip)

**Comment by Luffy7498** [comment]
How to add this plugin please help a noob brother

**Comment by Luffy7498** [comment]
No use, i updated repo with this zip file, still the same issue. Instead got extra channels that don't play and icons are all gone.

**Comment by Shap6565** [comment]
Music Channel YRF not working with above Jiotv Plugin. Kindly look into the matter please.

**Comment by Luffy7498** [comment]
No need now, found a perfect app for Indian TV. Its called CRICFy TV.

**Comment by sahaanup65** [comment]
> Hello,
> 
> i found the new kodi plugin where all sony channels are working, along with other chanels. here is the discord link:
> 
> https://discord.com/invite/bYSv8v6E
> 
> also plugin file. [plugin.video.jiotv-1.0.15.zip](https://github.com/krreet/plugin.video.jiotv/files/14179339/plugin.video.jiotv-1.0.15.zip)

Again Sony sports channels are not working 
Please do something to watch Sony sports channels
