### ISSUE TITLE
Channels can longer see catchup 

### ISSUE THREAD

**Issue by ranjeets9** [krreet/plugin.video.jiotv#130]
Channels can longer see catchup @krreet @tobalan can you please check and help here please. Thanks in Advance

**Comment by ranjeets9** [comment]
+ing @technofreak24 pls help

**Comment by technofreak24** [comment]
@ranjeets9 
**7 Days Catchup** feature works only for most of the Viacom18 (Colors) channels and some other general channels.
ZEE Entertainment channels do not offer Catchup and Sony Network has Catchup but not working in KODI.

**Comment by ranjeets9** [comment]
> @ranjeets9 **7 Days Catchup** feature works only for most of the Viacom18 (Colors) channels and some other general channels. ZEE Entertainment channels do not offer Catchup and Sony Network has Catchup but not working in KODI.

Thank you bro now I understand..
