### ISSUE TITLE
Follow up to -  None of the channels is loading / playing anymore just circles back to menu #132 

### ISSUE THREAD

**Issue by ranjeets9** [krreet/plugin.video.jiotv#136]
@technofreak24 @krreet @tobalan

Provided solution worked perfectly but later stopped and looking solutions online checking kiran repo and https://github.com/krreet/plugin.video.jiotv/releases and trying different versions of Kodi and plugin now totally lost track of what will work :-) Hence need your expert advise on which version of Kodi to go with which works both on PC and android TV along with which plugin to add on will be really appreciated 

Thank you all in advanced waiting to hear from you

**Comment by technofreak24** [comment]
@ranjeets9 The accesstoken is refreshed frequently in the official app and that process has to be implemented in the plugin too to ensure continuous playback without repeated login.
You can try https://github.com/kiranreddyrebel/plugin.video.jiotv

Repo: https://kiranreddyrebel.github.io/

**Comment by ranjeets9** [comment]
> @ranjeets9 The accesstoken is refreshed frequently in the official app and that process has to be implemented in the plugin too to ensure continuous playback without repeated login. You can try https://github.com/kiranreddyrebel/plugin.video.jiotv
> 
> Repo: https://kiranreddyrebel.github.io/

@technofreak24 re-login would not be an issue and what version of Kodi do you recommend > [kodi-20.5-Nexus-arm64-v8a.apk](https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-20.5-Nexus-arm64-v8a.apk) coz i need a version for my PC as well thanks

**Comment by ranjeets9** [comment]
> > @ranjeets9 The accesstoken is refreshed frequently in the official app and that process has to be implemented in the plugin too to ensure continuous playback without repeated login. You can try https://github.com/kiranreddyrebel/plugin.video.jiotv
> > Repo: https://kiranreddyrebel.github.io/
> 
> @technofreak24 re-login would not be an issue and what version of Kodi do you recommend > [kodi-20.5-Nexus-arm64-v8a.apk](https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-20.5-Nexus-arm64-v8a.apk) coz i need a version for my PC as well thanks

@technofreak24 never mind I checked the versions of android in the given link and got for windows https://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20240704-8642d8ca-master-x64.exe. Let me install and update thanks again

**Comment by ranjeets9** [comment]
> > > @ranjeets9 The accesstoken is refreshed frequently in the official app and that process has to be implemented in the plugin too to ensure continuous playback without repeated login. You can try https://github.com/kiranreddyrebel/plugin.video.jiotv
> > > Repo: https://kiranreddyrebel.github.io/
> > 
> > 
> > @technofreak24 re-login would not be an issue and what version of Kodi do you recommend > [kodi-20.5-Nexus-arm64-v8a.apk](https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-20.5-Nexus-arm64-v8a.apk) coz i need a version for my PC as well thanks
> 
> @technofreak24 never mind I checked the versions of android in the given link and got for windows https://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20240704-8642d8ca-master-x64.exe. Let me install and update thanks again

@technofreak24 Got it working in my PC with the provided version and plugin but some channels like sony does not work but rest is ok so something is better than nothing for now :-) thanks again 

Also I tried hotstar from the given repo seems to failing with error below. Let me know if this needs a new thread to be opened

![image](https://github.com/user-attachments/assets/e3fe3e6b-0593-4a81-a7d6-665aebcb57d0)

**Comment by ranjeets9** [comment]
Reported hotstar issue [at](https://github.com/kiranreddyrebel/kiranreddyrebel.github.io/issues/1) hence closing this thread
