### ISSUE TITLE
Working Repo with Jio Fix July 2024

### ISSUE THREAD

**Issue by dom007-rock** [krreet/plugin.video.jiotv#141]
Do star this repo! It will make dev happy for his efforts! 

https://github.com/kiranreddyrebel/plugin.video.jiotv

**Comment by cruiz24** [comment]
Stuck on loader after an error

**Comment by giridathac** [comment]
Can someone help me get 32 bit Kodi-v7 22.04 version? I will put this comment on Kiran's GitHub page as well..

**Comment by shri1990** [comment]
> Do star this repo! It will make dev happy for his efforts!
> 
> https://github.com/kiranreddyrebel/plugin.video.jiotv

Is this repo working even now?

**Comment by Parth2712002** [comment]
> Do star this repo! It will make dev happy for his efforts!
> 
> https://github.com/kiranreddyrebel/plugin.video.jiotv

Not working 😞

**Comment by DeekshithVelmula** [comment]
> Do star this repo! It will make dev happy for his efforts!
> 
> https://github.com/kiranreddyrebel/plugin.video.jiotv

@dom007-rock Hey is it working or not?

**Comment by dom007-rock** [comment]
Hey,
It is working and I am using it in my Tv.
Steps:
- Uninstalled if any old Kodi Tv
- Install the latest one from playstore
- Follow the steps mentioned in that "Repo"
Thanks!

**Comment by shri1990** [comment]
> Hey, It is working and I am using it in my Tv. Steps:
> 
> * Uninstalled if any old Kodi Tv
> * Install the latest one from playstore
> * Follow the steps mentioned in that "Repo"
> * Install the Add on 2.3.11
>   Thanks!

I followed the same steps but doesnt seem to work.. Still getting same error.

**Comment by dom007-rock** [comment]
It is working for me in android tv but not in pc app

**Comment by Parth2712002** [comment]
> Hey, It is working and I am using it in my Tv. Steps:
> 
> * Uninstalled if any old Kodi Tv
> * Install the latest one from playstore
> * Follow the steps mentioned in that "Repo"
> * Install the Add on 2.3.11
>   Thanks!

Not working bro
