### ISSUE TITLE
Key 19 error

### ISSUE THREAD

**Issue by akshayjauhari** [krreet/plugin.video.jiotv#18]
V 2.0.15 now gives Key 19 error. Please update

**Comment by KriezParker** [comment]
Unable to access Jio TV. Key 19 error comes on latest version. Please update

**Comment by jigarmd** [comment]
V 2.0.15 now gives Key 19 error. Please update

**Comment by Minkesh-tech** [comment]
before installing V2.0.15 it displayed key error 18. However, when installed V 2.0.15 it showed Key error 19. Please solve this bug and release a update version whish is error free.

**Comment by technofreak24** [comment]
KeyError 19 fixed, Audio working, Catchup from EPG/Channel Guide working version 2.0.15.1.zip (173 KB file size) on discord server https://discord.gg/uCsbem5B

**Comment by Ursgirishgupta** [comment]
> KeyError 19 fixed, Audio working, Catchup from EPG/Channel Guide working version 2.0.15.1.zip (173 KB file size) on discord server https://discord.com/channels/1069583196326469634/1069583197186293774/1076046640848326667

@technofreak24  unable to reach to the channel could you please reshare it

**Comment by ctct08** [comment]
> KeyError 19 fixed, Audio working, Catchup from EPG/Channel Guide working version 2.0.15.1.zip (173 KB file size) on discord server https://discord.com/channels/1069583196326469634/1069583197186293774/1076046640848326667

please share somewhere accessable. The link youp rovided isn't accessable

**Comment by technofreak24** [comment]
Added proper link on https://github.com/krreet/plugin.video.jiotv/issues/18#issuecomment-1434608310

**Comment by nabendu1** [comment]
Use thjs version 
https://github.com/nabendu1/plugin.video.jiotv/releases/tag/2.0.15_KeyErr19_LangMenu_Upd

**Comment by krreet** [comment]
fixed in 2.0.16

**Comment by Minkesh-tech** [comment]
> Use thjs version https://github.com/nabendu1/plugin.video.jiotv/releases/tag/2.0.15_KeyErr19_LangMenu_Upd

Its working ... Thank you for the update.
