### ISSUE TITLE
channel listing not working

### ISSUE THREAD

**Issue by pankajtejawat** [krreet/plugin.video.jiotv#24]
The 2.0.16 update does not load the channel list in the Simple PVR client.

**Comment by samykhan** [comment]
facing same issue with 2.0.17

**Comment by Madmdax** [comment]
Playlist (channel list) does not load in the app with the new update 2.0.17 !

**Comment by krreet** [comment]
Try kodi 19.4

**Comment by manojdjoshi** [comment]
playlist perfct work in kodi 19.5

**Comment by samykhan** [comment]
tried on kodi 19.5, working fine

**Comment by sun1423** [comment]
working on fine on kodi 20

**Comment by techgamers2** [comment]
> working fine on kodi 20

simple pvr client not working on 20 is it addon issue or kodi issue... should i wait for fix coz i dont want to downgrade

**Comment by pankajtejawat** [comment]
> working fine on kodi 20

Not working on Kodi 20 for me will check after downgrading.

**Comment by Madmdax** [comment]
> > working fine on kodi 20
> 
> simple pvr client not working on 20 is it addon issue or kodi issue... should i wait for fix coz i dont want to downgrade

Yes everything is working perfectly on 19.5 but not on Kodi 20 ! It is recommended to downgrade to kodi 19.5 and turn off auto update !

**Comment by techgamers2** [comment]
> > > working fine on kodi 20
> > 
> > 
> > simple pvr client not working on 20 is it addon issue or kodi issue... should i wait for fix coz i dont want to downgrade
> 
> Yes everything is working perfectly on 19.5 but not on Kodi 20 ! It is recommended to downgrade to kodi 19.5 and turn off auto update !

my query wasnt tht

**Comment by sun1423** [comment]
> working fine on kodi 20

on kodi 20 I'm using zip 17 without any issue

**Comment by techgamers2** [comment]
> > working fine on kodi 20
> 
> on kodi 20 I'm using zip 17 without any issue

can u provide step by step if u dont mind ...also hav to updated 19.5 to 20 or uninstall older version then install 20

**Comment by sun1423** [comment]
> > > working fine on kodi 20
> > 
> > 
> > on kodi 20 I'm using zip 17 without any issue
> 
> can u provide step by step if u dont mind ...also hav u updated 19.5 to 20 or uninstall older version then install 20

jiotv
try remove old 15 or 16  zip first, reboot, then install 17v ,reboot, 

kodi

 I had 19.1, I uninstalled that then installed 20

first give try to jio zip method

**Comment by krreet** [comment]
Fixed for Kodi 20 in 2.0.18
