### ISSUE TITLE
Not able to Install on fire stick

### ISSUE THREAD

**Issue by hmittal690** [krreet/plugin.video.jiotv#30]
I am pretty new to github and logging my issue here. Please pardon if its wrong place. 
I tried to download the latest zip file on my fire stick so that i can install from zip in kodi. But on trying to install zip file from kodi, the file is not visible under the folder it is downloaded, but the file is visible when i look through the downloader app in that folder.
 Can someone please help me. Not sure if its fire stick specific issue or something i am doing incorrectly. Any help would be appreciated. Thanks.

**Comment by technofreak24** [comment]
Missing Files, No Audio, Playback issues are commonly noted problems by Kodi Nexus v20.* users. 
Kodi Matrix v19.* is recommended to solve these issues.
I am also a Amazon FireTVStick 3rd Gen user without any problems and there are many FireTV Stick/Smart TV users on https://discord.gg/fj5HmBXY

**Comment by Karveanjali** [comment]
> I am pretty new to github and logging my issue here. Please pardon if its wrong place.
> I tried to download the latest zip file on my fire stick so that i can install from zip in kodi. But on trying to install zip file from kodi, the file is not visible under the folder it is downloaded, but the file is visible when i look through the downloader app in that folder.
> Can someone please help me. Not sure if its fire stick specific issue or something i am doing incorrectly. Any help would be appreciated. Thanks.

@hmittal690, downloaded file is missing extension .zip… just rename it to add extension then go back to Kodi to check.. it Will show up for installation

**Comment by krreet** [comment]
Refer firestick guide to install apps
