### ISSUE TITLE
Add the addon to your own repo

### ISSUE THREAD

**Issue by satyajitd111** [krreet/plugin.video.jiotv#33]
So that it can be automatically updated

**Comment by techgamers2** [comment]
yes i m tried of manually update but idont think he can do it coz its a fork btw kreet thx for fixing kodi 20 pvr iptv list issue

**Comment by sadiktamboli** [comment]
Plz give me full setp guide for auto update 
How can we do it

**Comment by tobalan** [comment]
use tobalan repo if needed
