### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by Debapatra2309** [krreet/plugin.video.jiotv#38]
Error in update please fix Jio V2.0.19
Kodi version 20.0
![Screenshot_2023-02-26-19-21-24-10_e18329511ee9ae4541720d804dbbeba9](https://user-images.githubusercontent.com/112774166/221414780-bf4821fe-4a87-4c2c-aaba-289d86d4d7e6.jpg)

**Comment by krreet** [comment]
Uninstall and reinstall kodi
