### ISSUE TITLE
Subtitles issue in animax 

### ISSUE THREAD

**Issue by SatoruMikami** [krreet/plugin.video.jiotv#39]
For some reason subtitles aren't showing or delayed from the actual subtitles in jio tv... please check it... not much of an issue though..but being a weeb it matters 😅... anyways thanks for putting your efforts making us smile

**Comment by krreet** [comment]
Hi please include by exactly how much is the subtitles delayed

**Comment by SatoruMikami** [comment]
> Hi , if possible please include by exactly how much is the subtitles delayed as i cant understand the language, so i am unable to find it out else i will need To run jiotv and kodi side by side

**Comment by SatoruMikami** [comment]
Well it's more like subtitles appearing issue rather than delayed subtitles issue... subtitles doesn't appear at all or if appears , vanishes in mid stream...I'm using kodi 20 Nexus with my stream quality set to medium+ ....and yeah please compare them side by side if possible...u will understand it more clearly then....Also whenever I comment the issue closes by itself...dunno maybe cuz I'm a noob in GitHub or something ,so sorry for the inconvenience

**Comment by tobalan** [comment]
Try 2.3.8

**Comment by imnoobless** [comment]
i am also facing kind of this issue, i m on kodi 20.2 and theres not even a drop of subtitles, i tried closing kodi multiple times stilll not working

**Comment by fatalcoder524** [comment]
Animax subtitles working??? Not for me in 2.3.9!

**Comment by reboot89** [comment]
It does not work in 2.3.8
