### ISSUE TITLE
Catch up

### ISSUE THREAD

**Issue by Karveanjali** [krreet/plugin.video.jiotv#4]
Could I request you to please fix catch-up feature?

**Comment by nabendu1** [comment]
@krreet the catchup feature is working fine when going into a particular channel from the JioTV plugin and then selecting the Catchup. 

However, when using Simple IPTV interface , the Channel Guide the Catch-up feature does not work . 

Adding a log file for your reference

https://pastebin.com/kMjs6ixR

**Comment by mk384456** [comment]
nick hindi,pogo,sonic,discovery kids, history tv 18 not working
mainly issue is of audio when as when go to my addons>input stream adaptive>settings>change media to vedio and restart kodi then these channel plays but without audio smoothly

for pogo use 
https://sjpurecdnems09.cdnsrv.jio.com/jiotvmblive.cdn.jio.com/bpk-tv/Pogo_Hindi_MOB/Fallback/Pogo_Hindi_MOB-audio_98834_hin=98800.m3u8

here audio_98834_hin=98800

please make changes in addon

**Comment by mk384456** [comment]
for more help use https://www.hotstar.eu.org/
for gathering correct channel links in jio tv addon
hoping for an update  regarding this 👏👏

**Comment by krreet** [comment]
fixed in 2.0.14

**Comment by Karveanjali** [comment]
Thank you 🙏🏻
