### ISSUE TITLE
Slowness/buffering in jiotv plugin

### ISSUE THREAD

**Issue by manjeet479** [krreet/plugin.video.jiotv#40]
Switch channel option work very slow...

**Comment by virubhai22** [comment]
EPG also not working

**Comment by sun1423** [comment]
Yes EPG not loading. 20 0 19

**Comment by manjeet479** [comment]
Any new version of plugin

**Comment by virubhai22** [comment]
epg still not working @krreet

**Comment by Kedharnadh** [comment]
Epg is working. Try to set-up couple of times and I'm not facing slowness as well

**Comment by manjeet479** [comment]
@Kedharnadh what exactly you have done to fix this.
