### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Karveanjali** [krreet/plugin.video.jiotv#44]
Addon not working 🙁
Getting TypeError - can concatenate only str (not “NonType”) to str

**Comment by krreet** [comment]
In setup epg?

**Comment by krreet** [comment]
Try 2.0.20 and also include the steps how to get this error

**Comment by zeros13213** [comment]
> Try 2.0.20 and also include the steps how to get this error

In 2.0.20 also it showing error. Even the steps u gave its not working. One channel is showing digishala named. When opening it shows type error

**Comment by Karveanjali** [comment]
TypeError Comes when any main categories is selected as Language, Genere etc.. No channel list is displayed 
I have added channels in Kodi favorites.. trying to run from there gives HTTP error

**Comment by zeros13213** [comment]
![Screenshot_20230305_224434.jpg](https://user-images.githubusercontent.com/68558684/222975483-60c3dfa8-480b-4f51-ac3b-b3eb550e97b4.jpg)

![Screenshot_20230305_224445.jpg](https://user-images.githubusercontent.com/68558684/222975493-0709d513-5f5c-4436-be3b-071021f1ebdc.jpg)

Just these 2 channels are showing & when it played error is showing

**Comment by shri1990** [comment]
> ![Screenshot_20230305_224434.jpg](https://user-images.githubusercontent.com/68558684/222975483-60c3dfa8-480b-4f51-ac3b-b3eb550e97b4.jpg)
> 
> ![Screenshot_20230305_224445.jpg](https://user-images.githubusercontent.com/68558684/222975493-0709d513-5f5c-4436-be3b-071021f1ebdc.jpg)
> 
> Just these 2 channels are showing & when it played error is showing

Yes same issue occurring for me aswell..

**Comment by krreet** [comment]
Use 2.0.21

**Comment by Karveanjali** [comment]
Works fine now. Thank you very much🙏🏻
