### ISSUE TITLE
ConnectionError for Catchup

### ISSUE THREAD

**Issue by Karveanjali** [krreet/plugin.video.jiotv#51]
Playing catch-up for the channel is resulting in ConnectionError..
Could you please look into it?

**Comment by Ursgirishgupta** [comment]
@krreet  in 20.0.23 bulit catchup is not working, also will you be able to fix the order of playlist as before, in new playlist my parents are facing issue in finding the channels the old one they are habitual of.

**Comment by sun1423** [comment]
looks lots of things messed up here

**Comment by Kedharnadh** [comment]
I'm not sure why everyone is complaining about things a lot.
Jio tv is working and every channel is working along with epg. 

Not sure what is messed up here. Developer is trying to keep the things up.

Give him some time

**Comment by krreet** [comment]
Setup epg from addon menu, it should work fine
