### ISSUE TITLE
It's stuck on creating m3u!

### ISSUE THREAD

**Issue by vedu346** [krreet/plugin.video.jiotv#56]

**Comment by sun1423** [comment]
yes it stucks, even not able to cancle it, finally has to close kodi n restart..

**Comment by techgamers2** [comment]
r u tryin to create m3u file from jiotv addon ? i dont think it will work

**Comment by vedu346** [comment]
> yes it stucks, even not able to cancle it, finally has to close kodi n restart.. 

Bro install the plugin
Then do to settings
Then setup
Then in channel api 1.3 turn it off 
Then click on setup epg 
N then setup pvr after that if you on the channel api it will work

**Comment by techgamers2** [comment]
oh u meant channel playlist ... but the title ws about m3u playlist

**Comment by vedu346** [comment]
> oh u meant channel playlist ... but the title ws about m3u playlist 

Nope its in kodi app !!

**Comment by krreet** [comment]
Fixed in 2.0.25

**Comment by techgamers2** [comment]
Now its stuck at pvr setup in progress

**Comment by techgamers2** [comment]
Workaround for stuck at pvr setup in progress : uninstall iptv simple pvr
client then setup it from jiotv addon it worked

**Comment by SatoruMikami** [comment]
@krreet I'm sorry but epg isn't loading again in 2.0.25...there's no option to setup epg in it...or maybe i don't know how to...a little help would be appreciated

**Comment by techgamers2** [comment]
> @krreet I'm sorry but epg isn't loading again in 2.0.25...there's no option to setup epg in it...or maybe i don't know how to...a little help would be appreciated

u need to uninstall simple iptv pvr plugin then go in jiotv addon settings then find set pvr playlist and it will automatically do the rest

**Comment by sun1423** [comment]
epg loading fine, but channels appear twice in channel list

**Comment by Kedharnadh** [comment]
> epg loading fine, but channels appear twice in channel list

You can open simple IPTV client settings and disable one from there.
