### ISSUE TITLE
Channel load and play issue

### ISSUE THREAD

**Issue by Marlinruno** [krreet/plugin.video.jiotv#58]
When a channel is Playing for long time like half hour or 1 hour or more than that, so no issue of buffering, BUT when switching to another channel from playing channel it starts loading to switch to the other channel, loading isn't issue but LOADING only happens and no channel change, also waited for like 5 minutes still the loading is happening no other further step happens, even if cleared cache and tried forcestop the kodi, same longtime loading happens, THANKYOU FOR DOING THIS SWEET THING DUDE👏👌

**Comment by Marlinruno** [comment]
And I'm using kodi 19.5

**Comment by Marlinruno** [comment]
Also same thing happening with kodi 20 version

**Comment by krreet** [comment]
> When a channel is Playing for long time like half hour or 1 hour or more than that, so no issue of buffering, BUT when switching to another channel from playing channel it starts loading to switch to the other channel, loading isn't issue but LOADING only happens and no channel change, also waited for like 5 minutes still the loading is happening no other further step happens, even if cleared cache and tried forcestop the kodi, same longtime loading happens, THANKYOU FOR DOING THIS SWEET THING DUDE👏👌

Try to use hls options true in iptv ovr addon advanced settings

**Comment by Kedharnadh** [comment]
I'm still facing same issue bro even after switching on hls option ☹️

> > When a channel is Playing for long time like half hour or 1 hour or more than that, so no issue of buffering, BUT when switching to another channel from playing channel it starts loading to switch to the other channel, loading isn't issue but LOADING only happens and no channel change, also waited for like 5 minutes still the loading is happening no other further step happens, even if cleared cache and tried forcestop the kodi, same longtime loading happens, THANKYOU FOR DOING THIS SWEET THING DUDE👏👌
> 
> Try to use hls options true in iptv pvr addon advanced settings

I'm still facing the same issue bro even after switching on hls option

**Comment by sadiktamboli** [comment]
Channel not playing if continue watching it for 10 min 
Plz provide solution with step by step guide so every one can use guidance 
Attached image of issue for reference 
Thanks in advance 
![IMG_20230321_212338](https://user-images.githubusercontent.com/49208418/226666613-1890825f-9bf6-4fd7-bf1c-3ceb4c390375.jpg)

**Comment by barbussian** [comment]
Hi
I would like to setup HOW I WANT and so optimizing in kodi via estuary screen, or info abort that suject )))
Have fun

**Comment by tobalan** [comment]
check 2.3.4 with fixes
