### ISSUE TITLE
Playing error

### ISSUE THREAD

**Issue by zeros13213** [krreet/plugin.video.jiotv#63]
Not getting played any channels. After clicking on channel it doesn't load.

Kodi version 19.5

**Comment by technofreak24** [comment]
Clear Cache in JioTV Addon Settings and Restart Kodi.
The channels will play then.
If you need latest updates check this discord https://discord.gg/MgtR9EQxz5

**Comment by zeros13213** [comment]
> Clear Cache in JioTV Addon Settings and Restart Kodi.
> The channels will play then.
> If you need latest updates check this discord https://discord.gg/MgtR9EQxz5

Not working

**Comment by techgamers2** [comment]
before opening an issue please specify kodi version and addon version

**Comment by techgamers2** [comment]
known issue is in kodi 20.1 the latest addon 2.0.25 may not work so switch back to kodi 20.0 and try again

**Comment by techgamers2** [comment]
update to kodi 20.0

**Comment by zeros13213** [comment]
> update to kodi 20.0 latest addon is more optimized for 20.0

Thanks
