### ISSUE TITLE
Jio tv 2.0.25 not working

### ISSUE THREAD

**Issue by Fjfjrixi** [krreet/plugin.video.jiotv#64]
Jio tv 2.0.25 zip not working please update time to time and fix

**Comment by techgamers2** [comment]
> Jio tv 2.0.25 zip not working please update time to time and fix

please dont demand update developer will update it in his free time its open source project u can also fork it and update

**Comment by techgamers2** [comment]
and yes if u use kodi 20.1 then addon may not work switch back to kodi 20.0

**Comment by sumitp9009** [comment]
@techgamers2    
After reinstalling jiotv addon working, 
thank you

**Comment by 29television** [comment]
Do anyone can guide how we can watch jio HD channels in 1080p from 720p in above plugin. If anyone know please mention the steps

**Comment by 29television** [comment]
> ok this is a quick guide > go to addon setttings > setup> more > set stream quality to best >apply all settings

Thanks but I have already done the above settings, I am asking about how can we watch hd channels in 1080p currently we r watching in 720p.

**Comment by techgamers2** [comment]
yes if the channel supports it then stream quality best is the highest setting .... this only works if u r on kodi 20.0

**Comment by techgamers2** [comment]
for example colors channel is in 720p whereas colors fhd is 1080p some hd channel only supports till 720p

**Comment by 29television** [comment]
> for example colors channel is in 720p whereas colors fhd is 1080p some hd channel only supports till 720p

Yes like in IPTV  some hd channels do support 1080p

**Comment by techgamers2** [comment]
its should be hd+ for 1080p like nick hd+ have 1080p not nick hd

**Comment by techgamers2** [comment]
you can try reset cache of addon and generate playlist again to best it should work

**Comment by 29television** [comment]
Jiotv plugin is not working in Kodi. Please provide solution.

**Comment by tmsani** [comment]
Jio tv plugin not working today. Anyone facing issues?

**Comment by technofreak24** [comment]
**Jio TV Plugin is working great as of now 8 May 2023!!**
**Jio TV v2.3.2** 
https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.2
![firetvstick3_041929](https://user-images.githubusercontent.com/121749085/236826270-4ec0258f-edfb-4242-bc0d-2abdfba0602b.png)

**InputStream Adaptive v20.3.7** 
https://github.com/xbmc/inputstream.adaptive/releases/tag/20.3.7-Nexus
**IPTV Simple Client Nexus  v20.10.1**
https://github.com/kodi-pvr/pvr.iptvsimple/releases/tag/20.10.1-Nexus

**Comment by AMEET82** [comment]
Since today morning this plugin is not working.

Pla solve, if anyone have solution.

**Comment by vijaysolanki10** [comment]
it stopped working since today morning.
@krreet (I am not a programmer though) I would really appreciate if you can explain what causes frequent failure and how we can fix it myself.

I checked the kodi.log, it shows "Failed with code 419:" after each channel url I tried to open.  It means the url is expired or it does not exist anymore.

TIA

**Comment by technofreak24** [comment]
Checked both plugin versions [**krreet v2.0.25**](https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25) and [**tobalan v2.3.3**](https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.3) are working great.
**You have to Logout and Login Again !!**
The login credential tokens expire on the 21st day from the previous login at the same time as observed by group members. There may be no need to re-login but only refresh the expired tokens with a click or auto-refresh triggered by a function in the python code.

**Comment by vijaysolanki10** [comment]
> Checked both plugin versions [**krreet v2.0.25**](https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25) and [**tobalan v2.3.3**](https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.3) are working great. **You have to Logout and Login Again !!** The login credential tokens expire on the 21st day from the previous login at the same time as observed by group members. There may be no need to re-login but only refresh the expired tokens with a click or auto-refresh triggered by a function in the python code.

Yes, both plugin versions are working after Logout and Logging in again. Sorry, I did not check that before. 
Thank you so much your input.
Is any of these plugin configured to refresh the expired tokens?

**Comment by rrjanbiah** [comment]
> > > Is any of these plugin configured to refresh the expired tokens?
> 
> Answer is No. Both the plugins are not configured to refresh the expired token because both the developers are not active in the [discord server](https://discord.gg/nnCgCQWb) and I am trying out python code edits as needed based on feedback and issue reporting from the discord members.

@techgamers2 I'm damn sure this feature was already available and working good till BotAllen https://github.com/botallen/plugin.video.jiotv/blob/fb0d191181da660f728d04e2c096409332c52c33/resources/lib/utils.py#L36

I even once posted a request to implement auto login and the BotAllen author replied me saying that this feature is already available for username & password, but cannot implement it for OTP based login. I then started using username & password based login and it was working good for longtime--till these recent fixes

**Comment by technofreak24** [comment]
> it was working good for longtime--till these recent fixes
Yes right. But even if the older version plugin from BotAllen original author is used now, this session headers expiry will happen with username-password/otp login. Another issue is "No Audio" for multi-language feed channels m3u8.

**Comment by technofreak24** [comment]
> it was working good for longtime--till these recent fixes

Yes right. But even if the older version plugin from BotAllen original author is used now, this session headers expiry will happen with username-password/otp login. Another issue is "No Audio" for multi-language feed channels m3u8.

**Comment by tobalan** [comment]
check 2.3.4 with fixes
