### ISSUE TITLE
Can't play as it silently fails from Apr 13

### ISSUE THREAD

**Issue by rrjanbiah** [krreet/plugin.video.jiotv#68]
When we open any channel, it tries to load, but quickly fails silently and also can't find anything in the log file. 

Happens from April 13th evening

Version: plugin.video.jiotv-2.0.25.zip

**Comment by techgamers2** [comment]
ya same happening to me
can u try to reinstall everything including kodi and botallen and jiotv plugin.. tell me the results

**Comment by technofreak24** [comment]
Your addon must be having old API url(s). It is working fine.👇🏿

![screenshot00007_081127](https://user-images.githubusercontent.com/121749085/232135196-705b5d47-1aff-4eec-8efa-b91702bbf0b4.png)

**Comment by rockynel** [comment]
I dont think you need botallen repository at all, as v2.0.25 is the latest and you can install addon through it.

**Comment by technofreak24** [comment]
There is no need of BotAllen repository or adding add-on source and the line <import addon="repository.botallen" version="2.0.0"/> in addon.xml file has to be removed to prevent addon installation error.
Same way there is no need of proxy server files/code which can cause problem.
If the channels are not playing then check the GET_CHANNEL_URL in constants.py is correct and update it if its not the latest.
Clearing Cache from add-on settings or reinstalling add-on may also help at times.

**Comment by technofreak24** [comment]
There is no need of BotAllen repository or adding add-on source and the line 
**import addon="repository.botallen" version="2.0.0"** in addon.xml file has to be removed to prevent addon installation error.
Same way there is no need of proxy server files/code which can cause problem.
If the channels are not playing then check the GET_CHANNEL_URL in constants.py is correct and update it if its not the latest.
Clearing Cache from add-on settings or reinstalling add-on may also help at times.

**Comment by techgamers2** [comment]
yes thx guys ....u guys were ryt it works without botallen ... i reset cache and directly installed jiotv addon and it fixed all issues for me ty

**Comment by technofreak24** [comment]
I remove repository and unnecessary dependencies, files/code from addons and then install them. Instead of auto-update from repositories, I install addons manually after checking the code.

![1681652774308_063258](https://user-images.githubusercontent.com/121749085/232537785-55fad46b-67cf-40cf-bb18-05a841c3ae68.jpg)

![1681652822100_063251](https://user-images.githubusercontent.com/121749085/232537883-fe421a6c-5b40-4e2e-af64-aac31428eb01.jpg)

**Comment by rrjanbiah** [comment]
Thanks everyone for your suggestion. 

I did nothing except logged out and login using email and password. It started to work again! (Previously cleared cache and that was not helpful)

Hence closing it for now. Thanks again
