### ISSUE TITLE
Audio not working in pogo channel 

### ISSUE THREAD

**Issue by mk384456** [krreet/plugin.video.jiotv#69]
Audia recently stopped working in pogo and other dual audio channels please fix as soon as possible 🙏🙏 thankyou in advance

**Comment by technofreak24** [comment]
It is an issue of **InputStream Adaptive** dependency of the Kodi addon giving No Audio on multi-language feed channels.
The solution is to change your version of **InputStream Adaptive** (either a previous version or newer version which plays audio)

**Comment by technofreak24** [comment]
Audio in all languages is now working for all Kids and Infotainment channels like Pogo, Nick, Discovery etc. [Solution is on this link](https://github.com/krreet/plugin.video.jiotv/issues/73)

**Comment by tobalan** [comment]
check 2.3.4 with fixes
