### ISSUE TITLE
nick hindi,pogo,sonic,discovery kids, history tv 18 not working, mainly issue is of audio when as when go to my addons>input stream adaptive>settings>change media to vedio and restart kodi then these channel plays but without audio smoothly  for pogo use https://sjpurecdnems09.cdnsrv.jio.com/jiotvmblive.cdn.jio.com/bpk-tv/Pogo_Hindi_MOB/Fallback/Pogo_Hindi_MOB-audio_98834_hin=98800.m3u8  here audio_98834_hin=98800  please make changes in addon.. for more help use https://www.hotstar.eu.org/ for gathering correct channel links in jio tv addon.

### ISSUE THREAD

**Issue by seniordevpants** [krreet/plugin.video.jiotv#7]
Posted as an issue from another user's comment

**Comment by shhahid7** [comment]
Good research @seniordevpants , this will surely help @krreet to fix this issue, lets see whenever he will get time to fix this issue, he will surely push the update.

anyways Special Request to @krreet if you are regularly following this project make changes in Officially BotAllen Repository zip file and put your JioTV upgradable link [ https://github.com/krreet/plugin.video.jiotv/releases ]
This will help to get update JioTV addon directly.

If you agree please proceed with changes in Official BotAllen Repository zip file.

Thanks & Appreciated you work and effort

**Comment by krreet** [comment]
fixed in 2.0.13 , use kodi 19.5 as kodi 20 has problem to run different audio stream so audio will be blank on kodi 20
