### ISSUE TITLE
Need updated version 2.0.26

### ISSUE THREAD

**Issue by Debapatra2309** [krreet/plugin.video.jiotv#70]

**Comment by technofreak24** [comment]
There may not be **v2.0.26** as there is no response in Discord server also. Take **v2.3.3** from https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.3

**Comment by Viraagj** [comment]
Plugin not working anymore

**Comment by technofreak24** [comment]
**Plugin is working great**, we have a troubleshooting post in discord group.
• Channels not playing - ReLogin after Logout
• Audio not there on multi lang channels - Downgrade InputStream Adaptive version
• HTTP Errors - Clear Cache & Relogin if needed
• Connection Lost : "Migrated Addon Error" - Delete extra/duplicate M3U instances in IPTV Simple Client.

**Comment by technofreak24** [comment]
**Plugin is working great**, we have a troubleshooting post in discord group.
• Channels not playing - ReLogin after Logout
• Audio not there on multi lang channels - Downgrade InputStream Adaptive version
• HTTP Errors - Clear Cache & Relogin if needed
• Connection Lost : "Migrated Addon Error" - Delete extra/duplicate M3U instances in IPTV Simple Client.

**New Home Screen - KODI Nexus v20.1**
![tv_screen_1_045007](https://user-images.githubusercontent.com/121749085/236500063-d80b726e-ea29-4ec3-8951-0eb8f76308f2.png)

**Comment by Viraagj** [comment]
Discord link

**Comment by Kedharnadh** [comment]
Where do we have v2.0.32

**Comment by Viraagj** [comment]
I m using 2.0.25

**Comment by Kedharnadh** [comment]
But the image shared by technofreak24 has version 2.0.32 that is where I'm wondering

**Comment by technofreak24** [comment]
![IMG_20230506_203824_084438](https://user-images.githubusercontent.com/121749085/236632834-fd6564b3-8870-4cf2-a587-3d9db7a13fd8.png)

![IMG_20230506_203842_084424](https://user-images.githubusercontent.com/121749085/236632843-45ae5bf2-70e3-43b1-9c93-7b6086bca27d.png)

**Comment by techgamers2** [comment]
> Plugin not working anymore

its working just relogin >> go to addon settings >> click logout >> login 
uninstall simple iptv addon and install it through jio kodi addon settings

**Comment by techgamers2** [comment]
and please dont demand for update developer will update it when he is free and if update is necessary

**Comment by AMEET82** [comment]
Since today morning this plugin version 2.0.25 is not working.

Developer plz solve.

**Comment by tobalan** [comment]
check 2.3.4 with fixes
