### ISSUE TITLE
how to install inputStream Adaptive add-on(older version) on kodi version 19.5 matrix for fixing audio issues

### ISSUE THREAD

**Issue by Taserwebs** [krreet/plugin.video.jiotv#71]

**Comment by techgamers2** [comment]
its exlusive to kodi version 20

**Comment by technofreak24** [comment]
> its exclusive to kodi version 20

No. Its NOT exclusive to KODI Nexus v20 , but it is for previous KODI versions too Matrix v19, Leia v18 too... Check on [InputStream Adaptive page on GitHub](https://github.com/xbmc/inputstream.adaptive).

**Comment by technofreak24** [comment]
> its exclusive to kodi version 20

**No. Its NOT exclusive to KODI Nexus v20**, but it is for also for KODI Omega v21 and previous KODI versions too like Matrix v19, Leia v18 too... Check on [InputStream Adaptive page on GitHub](https://github.com/xbmc/inputstream.adaptive).
I have just changed to KODI Omega v21.
![firetv_screenshot_051347](https://github.com/krreet/plugin.video.jiotv/assets/121749085/2cb9766e-45b3-4839-943f-bcd56b96f462)

**Comment by tobalan** [comment]
check 2.3.4 with fixes
