### ISSUE TITLE
Auto relogin for password login - feature request

### ISSUE THREAD

**Issue by manojmth** [krreet/plugin.video.jiotv#72]
Thank you very much for your work!

Please provide for auto logout-login after every 2-3 days (maybe feature and period can be offered as options) for password based logins. This is especially useful when setup for aged parents with the channels they watch in favourites. They will not be able to manually logout and log back in again. Thanks.

**Comment by rrjanbiah** [comment]
AFAIK, this feature is available from the beginning for the password based login. But it looks recently broken for some edge case. I now have to relogin approximately once in 25 days. 

(I also vote for it. Thanks)

**Comment by techgamers2** [comment]
how to get password based login do i hav to contact jio support for tht ?

**Comment by AMEET82** [comment]
Since today morning the plugin is not working.

Plz solve.

**Comment by snowdog05** [comment]
> Since today morning the plugin is not working.
> 
> Plz solve.

Plugin is working fine for me. If you facing issues, just log out and re-login into jiotv plugin and restart kodi. It should work.

**Comment by manojmth** [comment]
> how to get password based login do i hav to contact jio support for tht ?

There are some links still active for that, try this without +91
https://www.jio.com/selfcare/signup/forgot-password/

**Comment by technofreak24** [comment]
> Please provide for auto logout-login after every 2-3 days (maybe feature and period can be offered as options) for password based logins.

The login credential tokens expire on the 21st day from the previous login at the same time as observed by group members. There may be no need to re-login but only refresh the expired tokens with a click or auto-refresh triggered by a function in the python code.

**Comment by tobalan** [comment]
added
check 2.3.4 with fixes
