### ISSUE TITLE
Audio working on Multi-Lang AAC channels

### ISSUE THREAD

**Issue by technofreak24** [krreet/plugin.video.jiotv#73]
**Solved Audio Issue on Multi-Lang AAC channels** by the following edit and it is working perfect for Discord members.
[Discord link for edited plugin .zip file v2.3.4 with audio fixed](https://discord.com/channels/1069583196326469634/1069583197186293774/1114264897862246583)
Checked for Pogo, Nick, Discovery etc and audio stream is found to be fine.
**Works in KODI Nexus v20+ Only !**

![Screenshot_20230603-002705](https://github.com/krreet/plugin.video.jiotv/assets/121749085/2b3960c5-c633-45f8-bc14-e718168e0139)

![IMG_20230530_174841_054907](https://github.com/krreet/plugin.video.jiotv/assets/121749085/3f3fb10d-179a-44c8-b2ae-71f4f6a0cafa)

![screen-2023-05-30-1653412_050006](https://github.com/krreet/plugin.video.jiotv/assets/121749085/219f05e2-5dfc-425b-9fa4-3c97d1632f43)

![screen-2023-05-30-1652145_050012](https://github.com/krreet/plugin.video.jiotv/assets/121749085/fc86541f-a347-4ce2-b6d4-86eb4575a20a)

**Comment by technofreak24** [comment]
![screen-2023-05-30-1652145_050012](https://github.com/krreet/plugin.video.jiotv/assets/121749085/fc86541f-a347-4ce2-b6d4-86eb4575a20a)

**Comment by Marlinruno** [comment]
Can I get that discord group invite link

**Comment by technofreak24** [comment]
> Can I get that discord group invite link

Yes sure you can join us on https://discord.gg/RmqZHBFT (try to join within 7 days as link expires).

**Comment by Marlinruno** [comment]
Thanks a lot dude

**Comment by technofreak24** [comment]
> > 
> 
> Link not working

Try this https://discord.gg/uaW4Q5F9

**Comment by lavish440** [comment]
> > > 
> > 
> > 
> > Link not working
> 
> Try this https://discord.gg/uaW4Q5F9

Can you help me regarding an issue about inpustream-adaptive and Widevine?

**Comment by tobalan** [comment]
check 2.3.4 with fixes
