### ISSUE TITLE
EPG not working

### ISSUE THREAD

**Issue by snowdog05** [krreet/plugin.video.jiotv#76]
Hi, EPG is not working from past 2 days. can you look into this?
Thanks.

**Comment by technofreak24** [comment]
EPG will work only for [**tobalan v2.3.3**](https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.3) as confirmed working by users in [Discord server message link](https://discord.com/channels/1069583196326469634/1069583197186293774/1120620174576459836) 
EPG has stopped for addons where developers are not active.

**Comment by technofreak24** [comment]
> can you provide me link to join discord server?
Sure. This is the [KODI Addons Discord Server](https://discord.gg/MgtR9EQxz5) where JioTV, JioCinema, ZEE 5, Sony LIV and other addons are discussed with team of developers, testers, normal users/viewers.
https://discord.gg/MgtR9EQxz5

**Comment by tobalan** [comment]
check new release 2.3.4
