### ISSUE TITLE
Plugin stopped working from yesterday 

### ISSUE THREAD

**Issue by ranjeets9** [krreet/plugin.video.jiotv#78]
[2.0.25](https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25)

Plugin stopped working from yesterday  can someone please check and help. It lists the channel but clicking on it does not open the media to play cant find anything relevant in events log. Let me know anything more needed from me to diagnose 

Thanks a lot for your help in advance much appreciated 
![Capture](https://github.com/krreet/plugin.video.jiotv/assets/123510532/f848c0af-8fef-4f85-be93-41696226cd1c)

**Comment by Mujtiba** [comment]
@krreet  plugin not working

**Comment by ranjeets9** [comment]
Yes its not working @krreet @Mujtiba can you please help fix it thanks

**Comment by technofreak24** [comment]
Checked both plugin versions [**krreet v2.0.25**](https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25) and [**tobalan v2.3.3**](https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.3) are working great.
**You have to Logout and Login Again !!**
The login credential tokens expire on the 21st day from the previous login at the same time as observed by [**Discord server**](https://discord.gg/MgtR9EQxz5) members. 
In the next release on Discord or [**tobalan GitHub**](https://github.com/tobalan), there may be no need to re-login but only refresh the expired tokens with a click or auto-refresh triggered by a function in the python code.

**Comment by snowdog05** [comment]
Plugin is working fine. I am watching it now.
try to re-login and restart kodi.
if re-login doesnt work, reinstall addon and check.
only EPG is not working in this addon.

**Comment by technofreak24** [comment]
Checked both plugin versions [**krreet v2.0.25**](https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25) and [**tobalan v2.3.3**](https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.3) are working great.
Channels are playing, but EPG (Program Guide) will work only in  [**tobalan v2.3.3**](https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.3).
**You have to Logout and Login Again !!**
The login credential tokens expire on the 21st day from the previous login at the same time as observed by [**Discord server**](https://discord.gg/MgtR9EQxz5) members. 
In the next release on [**Discord**](https://discord.gg/MgtR9EQxz5) or [**tobalan GitHub**](https://github.com/tobalan), there may be no need to re-login but only refresh the expired tokens with a click or auto-refresh triggered by a function in the python code.

**Comment by ranjeets9** [comment]
@technofreak24 @snowdog05 awesome guys thanks a lot for your help yes after I re logged in all is working now. Dumb i dint try that myself. Until a new release I will keep in mind to re-login every 21st day again thanks :-)

**Comment by ranjeets9** [comment]
Resolved

**Comment by technofreak24** [comment]
[New version v2.3.4](https://github.com/krreet/plugin.video.jiotv/releases/tag/2.3.4) has released.
Thanks to tobalan and krreet from discord server.
Refresh token is not yet implemented but we are testing it on discord server.
