### ISSUE TITLE
2.3.4 cant play catchup anymore 

### ISSUE THREAD

**Issue by ranjeets9** [krreet/plugin.video.jiotv#80]
2.3.4 cant play catchup anymore nor see that option in any of the channels also can u tell me if anyone planning to add Hungama tamil channel to the list?

Much appreciated for your help / response and time.. thanks a lot

**Comment by Vikassm73** [comment]
[plugin.video.jiotv.zip](https://github.com/krreet/plugin.video.jiotv/files/11892972/plugin.video.jiotv.zip)

try this zip. If it is working. Krreet can cross check code and do necessary correction. Now it don;t required to import inputstream.adaptive so can be removed from addon.xml

**Comment by technofreak24** [comment]
Catchup is playing fine for [**krreet/tobalan v2.3.4**](https://github.com/krreet/plugin.video.jiotv/releases/tag/2.3.4)
The **Catchup** option appears as context menu on long press/right click/options menu button on the Channel Name.
![ss1_054609](https://github.com/krreet/plugin.video.jiotv/assets/121749085/fdf91692-210b-4856-92f2-1076c124283a)
However for easy access to select channels Catchup by filter on home screen, I tried this and it works great.
**Step 1 - Catchup Option**
![ss2_054600](https://github.com/krreet/plugin.video.jiotv/assets/121749085/7b8c78b2-d27a-4403-8e06-f16565373298)
**Step 2 - Catchup Channels**
![ss3_054617](https://github.com/krreet/plugin.video.jiotv/assets/121749085/35d29ff6-1e73-45c8-9dc9-86f58e61c789)
**Step 3 - Catchup Shows List**
![ss4_054613](https://github.com/krreet/plugin.video.jiotv/assets/121749085/69584065-24c6-4c3b-b462-7bf6bf813a05)

**Comment by ranjeets9** [comment]
Negative TV as the same issue as mentioned above no catch up unless I am doing something wrong pls help

**Comment by technofreak24** [comment]
> I only see the following right click or long press

This is **TV Channels** section of KODI.
Catchup video should play on clicking program name in the program guide (EPG).
Another option is in the **Add-ons** section of KODI, in JioTV addon open any channel with Catchup by Genre or Language and right-click/long press on the channel name. Catchup appears as an option in the context menu which when clicked gives catchup shows day-time list.

**Comment by technofreak24** [comment]
> doing something wrong pls help

Enable Catchup in the IPTV Simple Client addon Settings/Configuration.
Restart KODI and then check again.

**Comment by ranjeets9** [comment]
![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/4842d1be-1fc2-4e0f-8977-c6cac7c1ef85)

Did you mean here coz  i dont see an option for catch up?

**Comment by technofreak24** [comment]
Check all Tabs for Catchup Enabled option...I think its Timeshift tab

**Comment by technofreak24** [comment]
> I only see the following right click or long press

You are getting only total 1024 channels. Now 1030 channels are there in Channel List API v1.4 and 1.3
Turn OFF the API 3.0 switch in JioTV addon.
Turn ON the Generate Playlist on Startup.
Restart KODI and check to see 1030 channels in all.

**Comment by ranjeets9** [comment]
![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/01fe15bd-112b-4359-a0a2-eda661a950c0)

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/84257265-7c16-4592-99e6-9fec72543a91)

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/3280180a-5019-459a-8655-41321e585f76)


![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/1eb7f211-cc2b-451e-913e-b8b63c4234fb)


![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/0e72275e-d0db-4f64-8635-36915f2f59fb)

**Comment by ranjeets9** [comment]
> 

Tried but still 1024 channels listed any other way

**Comment by ranjeets9** [comment]
> 

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/f91b9458-8551-4bbf-bd33-3e17f151b340)

**Comment by technofreak24** [comment]
> Did you mean here coz i dont see an option for catch up?


Got it. Its the **Catchup** Tab at the end.
KODI Skin : Estuary
![estcatchup_071520](https://github.com/krreet/plugin.video.jiotv/assets/121749085/40ea748c-9bdc-4555-b89d-421a4fd24910)
KODI Skin : Quartz
![quartcatchup_071524](https://github.com/krreet/plugin.video.jiotv/assets/121749085/4f9ecc9a-648c-4510-8318-462591992b95)

**Comment by ranjeets9** [comment]
![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/d7a2c0ee-b36a-4633-9589-123534349ea2)

As soon as I enable and click ok error pop's up saying IPTV simple client connection lost same issue i reported earlier 

 IPTV simple client now shows connection lost #761

**Comment by technofreak24** [comment]
> error pop's up saying IPTV simple client connection lost 

It is because you have more than one instances of JioTV playlist created by Kodi. Try to keep only one instance.

**Comment by technofreak24** [comment]
> reinstall then? please advise but I have done this reinstall many times earlier as well

No. No need to reinstall, just remove extra instances.

**Comment by technofreak24** [comment]
> trying to enable catchup comes with the same error again **IPTV simple client connection lost**

Is playlist.m3u of JioTV add-on in any of the instances? Just keep it.
Are you doing Setup PVR ? Turn OFF Generate Playlist on Startup in add-on Settings.
It is plugin's programmatic access to IPTV Simple Client that is causing all this "connection lost" issues.

**Comment by ranjeets9** [comment]
> > trying to enable catchup comes with the same error again **IPTV simple client connection lost**
> 
> Is playlist.m3u of JioTV add-on in any of the instances? Just keep it. Are you doing Setup PVR ? Turn OFF Generate Playlist on Startup in add-on Settings. It is plugin's programmatic access to IPTV Simple Client that is causing all this "connection lost" issues.

Hi @technofreak24, you are a genius and here is what i did on my desktop and smart TV removed Migrated Add-on Config and edited the highlighted instead of adding another see below 

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/7c318452-f3e5-4117-8ca9-0da30c45816c)

Here i could enable catch up and all if fine working but stil have 1024 channels 

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/e1d34a34-e932-4116-94a6-7fb19590962f)

**Comment by ranjeets9** [comment]
API 3.0 is turned off and how do i set channels list to 1.4 dont see any settings

**Comment by technofreak24** [comment]
> API 3.0 is turned off and how do i set channels list to 1.4 dont see any settings

Turning OFF API 3.0 automatically makes Channel List 1.4 active.
Do **Clear Cache** in JioTV Addon settings.
Playlist has to be generated on startup once, by turning it ON and Restarting KODI.

**Comment by ranjeets9** [comment]
Perfect API 3.0 is turned off and cleared cache restarted Kodi and playlist generated turned off generate playlist applied settings now I see zee ganga 129th channel still missing one channel then?

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/ee7191d5-4396-4f51-886e-d4264349e9ae)

**Comment by ranjeets9** [comment]
I can live with it unless u have anything? if not thanks a lot again @technofreak24

**Comment by Alexios775** [comment]
> Catchup is playing fine for [**tobalan's plugin v2.3.4**](https://github.com/krreet/plugin.video.jiotv/releases/tag/2.3.4) or [**krreet's plugin v2.3.4**](https://github.com/krreet/plugin.video.jiotv/releases/tag/2.3.4). The **Catchup** option appears as context menu on long press/right click/options menu button on the Channel Name. ![ss1_054609](https://user-images.githubusercontent.com/121749085/249461400-fdf91692-210b-4856-92f2-1076c124283a.png) However for easy access to select channels Catchup by filter on home screen, I tried this and it works great. **Step 1 - Catchup Option** ![ss2_054600](https://user-images.githubusercontent.com/121749085/249462174-7b8c78b2-d27a-4403-8e06-f16565373298.png) **Step 2 - Catchup Channels** ![ss3_054617](https://user-images.githubusercontent.com/121749085/249462384-35d29ff6-1e73-45c8-9dc9-86f58e61c789.png) **Step 3 - Catchup Shows List** ![ss4_054613](https://user-images.githubusercontent.com/121749085/249462555-69584065-24c6-4c3b-b462-7bf6bf813a05.png)

Which skin is this?

**Comment by technofreak24** [comment]
> Which skin is this?

I am using **Quartz** KODI  skin. **Quartz** is a light-weight skin with a intuitive user interface and highly customizable home screen.
https://kodi.tv/addons/nexus/skin.quartz

https://kodi.tv/addons/matrix/skin.quartz

https://github.com/nonJon/skin.quartz

**Comment by Alexios775** [comment]
> > Which skin is this?
> 
> I am using **Quartz** KODI skin. **Quartz** is a light-weight skin with a intuitive user interface and highly customizable home screen. https://kodi.tv/addons/nexus/skin.quartz
> 
> https://kodi.tv/addons/matrix/skin.quartz
> 
> https://github.com/nonJon/skin.quartz

Thanks
