### ISSUE TITLE
The dependency on inputstream.adaptive version 20.3.2 could not be satisfied.

### ISSUE THREAD

**Issue by rrjanbiah** [krreet/plugin.video.jiotv#82]
Device: Firestick
Version: 2.3.4 by @tobalan 
Kodi version: 20.2, 20.1, 19.5 via TROYPOINT toolbox

I was using Kodi Matrix and as it got crashed (due to pendrive corruption as I installed it in external storage), I was trying tivi and Movian. Though they are butter smooth Jio didn't work for me. 

So, I started Kodi from the scratch and clean through TROYPOINT toolbox. I was getting `The dependency on inputstream.adaptive version 20.3.2 could not be satisfied.` whenever I tried to install the Jio plugin. I was downgrading through clean install till 19.5. Then I thought that it is expecting the exact `20.3.2` Kodi version which seems yet to be released.

So, this looks like a bug on a fresh install?

**Comment by rrjanbiah** [comment]
Sorry, but looks similar to #62

**Comment by jigarmd** [comment]
same here

**Comment by rrjanbiah** [comment]
With the latest 2.3.6 by @tobalan from https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.6 getting the below error:


`The dependency on repository.tobalan version 2.0.1 could not be satisfied.`

**Comment by tobalan** [comment]
Check 2.3.7
