### ISSUE TITLE
JioTV error, check the log for more info

### ISSUE THREAD

**Issue by XDAGamer** [krreet/plugin.video.jiotv#83]
so im getting this error since last night, i tried for hours and even in morning today i have already tried alot.

I was watching Cartoon Network last night then suddenly something happened playback stopped working.

I have seen couple of other errors too including streamhelper couldn't be satisfied somehow managed to crossover that

i have tried kodi version 19.5, 20.1, 20.0 and the latest 20.2 as well but none of them seem to work.

I have also tried clean install removing cache and settings but no luck.

**Comment by technofreak24** [comment]
The solution was found last night on [Discord server](https://discord.gg/MgtR9EQxz5) as many members faced the same issue.
Its an update of requests module addon that is causing problem and solution is downgrade of requests module.
Here is how we discussed and solved on [our Discord server](https://discord.com/channels/1069583196326469634/1069583197186293774/1126587789027332186) 
Step 1: set auto update off
Step 2: download script.module.requests-2.27.1+matrix.1.zip from here
https://mirrors.kodi.tv/addons/matrix/script.module.requests/
Step 3: Install the above zip in kodi
 
Screenshot below:
![Screenshot_20230707-064832](https://github.com/krreet/plugin.video.jiotv/assets/121749085/86857c06-3d5d-4bc2-87c4-a77b7c47c206)

**Comment by XDAGamer** [comment]
thanks, it worked :)

**Comment by Madmdax** [comment]
> thanks, it worked :)

Could you help with installation steps ! I'm not able to install it ! The error is still there for me !

**Comment by ParthivSavani4582** [comment]
Thanks @technofreak24 worked for me.

@Madmdax Here are the steps.

Step 1: In KODI > Settings/System > Add-ons > Set auto-updates of Add-ons OFF by choosing Notify, but don't install updates.

Step 2. Uninstall existing JioTv add-on

Step 3: Download [script.module.requests-2.27.1+matrix.1.zip](https://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.27.1+matrix.1.zip)

Step 4: Install the above zip in KODI

Step 5: Install JioTv add-on.

Done

**Comment by KA-GT** [comment]
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'HTTPResponse' from 'requests.adapters' (C:\Users\matad\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\matad\AppData\Roaming\Kodi\addons\plugin.video.jiotv\service.py", line 3, in <module>
                                                       from resources.lib import proxy
                                                     File "C:\Users\matad\AppData\Roaming\Kodi\addons\plugin.video.jiotv\resources\lib\proxy.py", line 10, in <module>
                                                       from resources.lib.utils import login, sendOTPV2
                                                     File "C:\Users\matad\AppData\Roaming\Kodi\addons\plugin.video.jiotv\resources\lib\utils.py", line 6, in <module>
                                                       import urlquick
                                                     File "C:\Users\matad\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 63, in <module>
                                                       from requests.adapters import HTTPResponse
                                                   ImportError: cannot import name 'HTTPResponse' from 'requests.adapters' (C:\Users\matad\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py)
                                                   -->End of Python script error report<--

**Comment by KA-GT** [comment]
Getting this error

**Comment by technofreak24** [comment]
> Getting this error

**The Solution is given above. Follow the steps given on** https://github.com/krreet/plugin.video.jiotv/issues/83#issuecomment-1624504638

**Comment by techgamers2** [comment]
instead of workaround fix can we get this fix implemented in next jiotv plugin update @tobalan

**Comment by technofreak24** [comment]
> instead of workaround fix can we get this fix implemented in next jiotv plugin update or its an kodi issue

It is not KODI issue, but the **script.module.requests** update that breaks other video playback addons as reported yesterday by Tobalan on discord. 
Fix is already implement in today's release.

**Comment by ranjeets9** [comment]
I followed exactly what is given by @technofreak24 but i still get the same Jio tv error cant find anything in logs followed thrice already 

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/daca50f5-5dff-44b6-8d53-16cb995b8e09)

nothing in events even after setting to error - warning

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/b79ecf6a-0b43-495e-bb71-cce5211e51b8)

some help here same issue on both PC and smart tv

**Comment by techgamers2** [comment]
Partial fix is already implemented in today's plugin release. We hope **script.module.requests** team also takes note and corrects it.

thanks @tobalan @technofreak24 for the fix .... will krreet repo also get update ?

**Comment by techgamers2** [comment]
> Partial fix is already implemented in today's plugin release. We hope **script.module.requests** team also takes note and corrects it.
> 
> thanks @tobalan @technofreak24 for the fix .... will krreet repo also get update ?



> Partial fix is already implemented in today's plugin release.
> We hope **script.module.requests** team also takes note and corrects it.

thanks @tobalan @technofreak24 for the fix .... will krreet repo also get update ?

**Comment by techgamers2** [comment]
> Partial fix is already implemented in today's plugin release.

thanks @tobalan @technofreak24 for the fix .... will krreet repo also get update ?

**Comment by technofreak24** [comment]
> thanks @tobalan @technofreak24 for the fix .... will krreet repo also get update ?

Yes [**tobalan's GitHub**](https://github.com/tobalan/plugin.video.jiotv) updates will appear in [**krreet's GitHub**](https://github.com/krreet/plugin.video.jiotv)
Check in the Releases it will show.
and on Discord server also in pinned messages.

**Comment by technofreak24** [comment]
> some help here same issue on both PC and smart tv

@ranjeets9 Check the **script.module.requests** dependency version. Most probably it is causing this error.
Go to JioTV Addon context menu (right click menu) and click Information. 
Then in Information see Dependencies and check **requests** version installed...it should be **2.27.1+matrix.1**

**Comment by technofreak24** [comment]
**Everyone** Great News !!! Screenshot below

**tobalan** *Today at 5:53 PM*
Tomorrow the request issue might be fixed, then the zip step may not be needed
![Screenshot_20230709-175350](https://github.com/krreet/plugin.video.jiotv/assets/121749085/239be67d-fda7-4994-8abf-532aa6ea6cdb)

**Comment by taslimansari-dew-frontend** [comment]
Worked for me.. Thanks 👏👏

**Comment by ranjeets9** [comment]
@technofreak24 I see the below

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/1749daa7-85be-4229-8ef3-4c8e51f31704)

Shall i wait for the new update tomorrow or u have any solution for me? thanks

**Comment by ranjeets9** [comment]
I see 2.3.7 release already which says bug fix https://github.com/krreet/plugin.video.jiotv/releases/tag/2.3.7. I will wait for one of your experts advise?

**Comment by ranjeets9** [comment]
also Kodi v20.2 (Nexus) https://kodi.tv/download/windows/

**Comment by technofreak24** [comment]
> Shall i wait for the new update tomorrow or u have any solution for me? thanks

Your **requests** dependecy version is **2.31.0** that breaks JioTV and many other video addons all over the world that depend on requests. It should be **2.27.1+matrix.1**
If you want to fix right now downgrade or else if you can wait for one or two days for **requests** to get fixed then its your choice.

**Comment by ranjeets9** [comment]
I tried to install but when it check the update it shows only 2.31.0 and I have uninstalled JIO tv add on 

![image](https://github.com/krreet/plugin.video.jiotv/assets/123510532/bc9dafc9-e14e-454d-a869-0836bc998a77)

**Comment by m3nt4lmind** [comment]
dhanyawad priya bhai. ab sabkuch sahi se chal raha hai. Great _/\_

**Comment by janumsw** [comment]
Thanks so much it's working 😁

**Comment by technofreak24** [comment]
> Thanks so much it's working 😁

Join our [**KODI Addons Discord Channel**](https://discord.gg/ydHvRHxV) in 5 days, link will expire after 5 days.

**Comment by naveenbnn** [comment]
this Http error is still coming in the jio tv with kodi app, is there any latest solutions avaiable?
