### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by samrth012** [krreet/plugin.video.jiotv#85]
Kodi version - 20.2 matrix 
Jio tv plugin - 2.3.7 

Failed to install and update - 

The dependency on repository.tobalan version 2.0.1 could not be satisfied.

Did you add your own repository? If yes please provide the repository link to install or the files

**Comment by techgamers2** [comment]
https://tobalan.github.io/

**Comment by samrth012** [comment]
yeah got it was just checking the build updates found out he has created his own respository appreciate your work man really needed it @tobalan thanks for the work man 
https://tobalan.github.io/

**Comment by rrjanbiah** [comment]
I don't think the repo is working. Getting the below error:

TobAlan Repository

Could not connect to repository.

**Comment by samrth012** [comment]
You need to restart Kodi once again

**Comment by techgamers2** [comment]
> I don't think the repo is working. Getting the below error:
> 
> TobAlan Repository
> 
> Could not connect to repository.

jio default dns may block some github request in kodi try switching dns to cloudflare and try again.... or use manual zip install method

**Comment by samrth012** [comment]
> I don't think the repo is working. Getting the below error:
> 
> TobAlan Repository
> 
> Could not connect to repository.
> 

Just follow the guide on website step by step restart Kodi it works later ok after few minutes and u can install jio tv directly from there I was having the same issue forgot to restart so wasn't working

**Comment by rrjanbiah** [comment]
Thank you @samrth012 and @techgamers2 

Yes, restarting helped. It installed the plugin and getting check log error without the log (looks #83). Getting the same error in manual method too.

Now, trying to install the request module manually and will keep you posted about the progress

**Comment by samrth012** [comment]
> Thank you @samrth012 and @techgamers2 
> 
> Yes, restarting helped. It installed the plugin and getting check log error without the log (looks #83). Getting the same error in manual method too.
> 
> Now, trying to install the request module manually and will keep you posted about the progress 

Yes request module needs to be fixed manually and the updates need to be stopped for it, there is some error with the newer request module

**Comment by rrjanbiah** [comment]
> Yes request module needs to be fixed manually and the updates need to be stopped for it, there is some error with the newer request module

Thank you @samrth012 Yes that worked. 

But, unfortunately, when I tried to login using username/email and password, it's showing

Login failed
Unknown error

Trying to reinstall again now

**Comment by samrth012** [comment]
> 
> > Yes request module needs to be fixed manually and the updates need to be stopped for it, there is some error with the newer request module
> 
> Thank you @samrth012 Yes that worked. 
> 
> But, unfortunately, when I tried to login using username/email and password, it's showing
> 
> Login failed
> Unknown error
> 
> Trying to reinstall again now
> 

Reinstall Kodi if possible start from scratch reinstall the module once and STOP automatic updates then install the tobalan repository restart again then install jio tv then it would work fine

**Comment by samrth012** [comment]
> 
> > Yes request module needs to be fixed manually and the updates need to be stopped for it, there is some error with the newer request module
> 
> Thank you @samrth012 Yes that worked. 
> 
> But, unfortunately, when I tried to login using username/email and password, it's showing
> 
> Login failed
> Unknown error
> 
> Trying to reinstall again now
> 

You might not have stopped updates and it would have got updated

**Comment by rrjanbiah** [comment]
> You might not have stopped updates and it would have got updated

Thank you @samrth012  for being extremely kind here. I double checked that the updates are turned off. I can see that request module 2.31.0 is waiting to get update upon confirmation:

```
Warning!

Add-on: requests
Origin: Manually installed
Version: 2.27.1+matrix.1
 will be uninstalled and replaced. Would you like to proceed?
```

I am trying to redo everything from the scratch once again

**Comment by samrth012** [comment]
> 
> > You might not have stopped updates and it would have got updated
> 
> Thank you @samrth012  for being extremely kind here. I double checked that the updates are turned off. I can see that request module 2.31.0 is waiting to get update upon confirmation:
> 
> ```
> Warning!
> 
> Add-on: requests
> Origin: Manually installed
> Version: 2.27.1+matrix.1
>  will be uninstalled and replaced. Would you like to proceed?
> ```
> 
> I am trying to redo everything from the scratch once again 

Sure will be here for hours or two do keep me updated I will help you side by side

**Comment by rrjanbiah** [comment]
> Sure will be here for hours or two do keep me updated I will help you side by side

@samrth012 I am extremely sorry for not updating immediately. I tried for a couple of times and as nothing worked, I gave up. Will check again sometime in this week. Again sorry for my poor response

**Comment by samrth012** [comment]
> 
> > Sure will be here for hours or two do keep me updated I will help you side by side
> 
> @samrth012 I am extremely sorry for not updating immediately. I tried for a couple of times and as nothing worked, I gave up. Will check again sometime in this week. Again sorry for my poor response
> 
> 

No problem just do one thing uninstall Kodi and start from fresh in this order 

Install Kodi 
Then from #83 
In KODI > Settings/System > Add-ons > Set auto-updates of Add-ons OFF by choosing Notify, but don't install updates.
Download script.module.requests-2.27.1+matrix.1.zip from https://mirrors.kodi.tv/addons/matrix/script.module.requests/
Install the above zip in KODI
Restart KODI 
Go to the Kodi file manager.
Click on "Add source"
The path for the source is https://tobalan.github.io/ (Give it the name "TobAlan Repo").
Go to "Addons"
In Addons, install an addon from zip. When it asks for the location, select "TobAlan Repository", and install repository.tobalan-2.0.1.zip.
Restart Kodi
Go back to Addons install, but this time, select "Install from repository"
Select the "Tobalan Repository"
Go into the "Video add-ons" section in the repo, and you'll find all video add-ons

Then i am sure it will be done surely 🥰
Hope it helps just follow in the exact order

**Comment by rrjanbiah** [comment]
> Then i am sure it will be done surely 🥰 Hope it helps just follow in the exact order

@samrth012 sure. Thank you so much, will try sometime later.

**Comment by samrth012** [comment]
> 
> > Then i am sure it will be done surely 🥰 Hope it helps just follow in the exact order
> 
> @samrth012 sure. Thank you so much, will try sometime later. 

Sure
