### ISSUE TITLE
2.3.7 update error

### ISSUE THREAD

**Issue by Rajat1200** [krreet/plugin.video.jiotv#87]
![IMG_20230716_203039](https://github.com/krreet/plugin.video.jiotv/assets/102061180/20dc8b7d-43ce-4a12-b7c2-1d3ef5c12399)
![IMG_20230716_203035](https://github.com/krreet/plugin.video.jiotv/assets/102061180/aba511bc-165e-482d-9644-bd9326e09d96)
 Plz help to update

**Comment by Rajat1200** [comment]
Problem while update 2.3.7

**Comment by technofreak24** [comment]
@Rajat1200 
> Problem while update 2.3.7

*⚠️ Installing repository (repo) is a must to install JioTV addon and get updates installed directly from repo (without downloading JioTV addon zip) !**
**JioTV addon zip cannot be directly installed.**
• In KODI, Add Source in File Manager
Name: TobAlan Repo
Path: https://tobalan.github.io/
• Install the **repository.tobalan-2.0.1.zip**
• 👉**Restart KODI** *(to avoid error "Could not connect to repository")*
• Go back to Addons install, but this time, select "Install from repository"
Select the **"TobAlan Repo"**
Go into the "Video add-ons" section in the repo, you'll find **JioTV add-on**. Install it.
[TobAlan's GitHub](https://github.com/tobalan/plugin.video.jiotv)
or
[krreet's GitHub](https://github.com/krreet/plugin.video.jiotv)

**Comment by technofreak24** [comment]
> @Rajat1200 : Plz help to update
Problem while update 2.3.7

*⚠️ Installing repository (repo) is a must to install JioTV addon and get updates installed directly from repo (without downloading JioTV addon zip) !**
**JioTV addon zip cannot be directly installed.**
• In KODI, Add Source in File Manager
Name: TobAlan Repo
Path: https://tobalan.github.io/
• Install the **repository.tobalan-2.0.1.zip**
• 👉**Restart KODI** *(to avoid error "Could not connect to repository")*
• Go back to Addons install, but this time, select "Install from repository"
Select the **"TobAlan Repo"**
Go into the "Video add-ons" section in the repo, you'll find **JioTV add-on**. Select it to install **JioTV addon**.
That's it. Login and watch it.

_______________________________________________
[TobAlan's GitHub](https://github.com/tobalan/plugin.video.jiotv)
or
[krreet's GitHub](https://github.com/krreet/plugin.video.jiotv)

**Comment by ASDRMS** [comment]
TobAlan's GitHub

**Comment by techgamers2** [comment]
u need to install tobolan repo 

for detailed instruction check this out [tobolan repo](https://tobalan.github.io/)

**Comment by Rajat1200** [comment]
Solved sir thankyou

**Comment by tobalan** [comment]
> Solved sir thankyou
