### ISSUE TITLE
Channel Switching Taking Time 

### ISSUE THREAD

**Issue by NirajIngole** [krreet/plugin.video.jiotv#93]
Is there any way to resolve the time taken while switching channels ?

Currently taking too much loan time when we switch channel & its not a network issue

**Comment by ASDRMS** [comment]
Use fast broadband

**Comment by NirajIngole** [comment]
> Use fast broadband

Its not a network issue

**Comment by technofreak24** [comment]
@NirajIngole @ASDRMS 

Channels are now switching and loading faster ( ≈ 3 seconds time).
Solution on this link https://github.com/krreet/plugin.video.jiotv/issues/96#issuecomment-1663430735
