### ISSUE TITLE
Taking time to load channel

### ISSUE THREAD

**Issue by Devil45677** [krreet/plugin.video.jiotv#96]
Taking lots of time to load any channel..... Taking too much time to move from one channel to other

**Comment by technofreak24** [comment]
Solution given by Discord member:
• Change Stream Type to **"Adaptive" (HLS)** in **InputStream Adaptive Settings**

**Comment by Devil45677** [comment]
Can any one help me with this...

**Comment by technofreak24** [comment]
Update the channel playback headers in main.py file of addon and channel switching and channel loading becomes quick ( ≈ 3 seconds time )👇

![IMG_20230803_124135_124203](https://github.com/krreet/plugin.video.jiotv/assets/121749085/f6281b8b-3196-4dab-86fa-90862c0bc9f0)

**Comment by Devil45677** [comment]
Can u tell me full path how to update payback_header  under main. Py..... I am unable to find main. Py file...... 
Please help me with this

**Comment by technofreak24** [comment]
@Devil45677 The developers krreet and tobalan will release an update on weekend to solve this by  editing the code.
in the zip addon, after extracting go to extracted folder and open main.py file ( path resources/lib/main.py).
There look for def play() and add the getUrlHeaders and call it.

**Comment by Devil45677** [comment]
I am confused.... Where should I go first to find main. Py

**Comment by Devil45677** [comment]
And how to extract code

**Comment by Devil45677** [comment]
Help me on this

**Comment by Devil45677** [comment]
Where can I get zip addon..... And how to extract it..... Please tell me full procedure from start to end

**Comment by Devil45677** [comment]
Please tell me full procedure.........

**Comment by Devil45677** [comment]
I despretly need it

**Comment by nikhilprasad** [comment]
> Please tell me full procedure.........

Same here. Where can I find the steps to hook this into Kodi please.

**Comment by Devil45677** [comment]
Can any one help us....

**Comment by technofreak24** [comment]
@Devil45677 @nikhilprasad 
Here is the updated zip folder with delay fix.
[fix_delay_plugin.video.jiotv-2.3.8.zip](https://github.com/krreet/plugin.video.jiotv/files/12260238/fix_delay_plugin.video.jiotv-2.3.8.zip)

**Comment by technofreak24** [comment]
@nikhilprasad Just do **Install Addon by Zip** in KODI Addon Settings. Restart KODI and check.
Nothing else needed.

**Comment by NewbieH4x** [comment]
@technofreak24  Can you please share the discord link? I would like to join and stay updated.

**Comment by technofreak24** [comment]
> @NewbieH4x Can you please share the discord link?

Join on [**KODI Addons and Streaming Discord**](https://discord.gg/yPGu5XbrB2)

**Comment by Devil45677** [comment]
Still same..... Still taking too much time
To switch channel........ Nothing has changed....

**Comment by Devil45677** [comment]
Can any one help me out here

**Comment by tobalan** [comment]
Try new option in 2.3.9

**Comment by tjagad** [comment]
Hi,

Even after using the new option in 2.3.9 I'm seeing almost 5 mins delay for the channels to start playing.

I've tried cleaning the cache, reinstalling kodi, etc but the issue is always reproducible. Any help on the matter is appreciated.

Thanks.

**Comment by technofreak24** [comment]
> @tjagad Even after using the new option in 2.3.9 I'm seeing almost 5 mins delay for the channels to start playing.

The delay in switching/loading channels in noted for non-Jio networks as per our [**KODI Addons Discord**](https://discord.gg/BTMapY8FkQ)  members reviews.
Try to use any Jio 4G LTE Mobile Phone Hotspot or Jio 4G Portable WiFi Router/Jio Fiber or Hathway (Reliance-Jio) Cable Internet.

**Comment by technofreak24** [comment]
> @technofreak24 Can you please share the discord link? I would like to join and stay updated.

Join on this link [**KODI Addons Discord**](https://discord.gg/BTMapY8FkQ)
